package com.aichat.app.tools;

import com.aichat.app.graph.DatePlanState;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Map;

/**
 * PDF 生成工具（iText 9 简化版）
 */
@Component
@Slf4j
public class PdfGenerationTool {

    public String generate(DatePlanState state) {
        String dir = System.getProperty("user.dir") + "/tmp";
        new File(dir).mkdirs();
        String pdfPath = dir + "/date-plan-" + System.currentTimeMillis() + ".pdf";

        try (PdfWriter writer = new PdfWriter(new FileOutputStream(pdfPath));
             PdfDocument pdf = new PdfDocument(writer);
             Document doc = new Document(pdf)) {

            String date = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));

            doc.add(new Paragraph("Date Plan"));
            doc.add(new Paragraph(date));
            doc.add(new Paragraph(""));
            doc.add(new Paragraph("Location: " + state.getDateLocation()));
            doc.add(new Paragraph("Budget: " + state.getDateBudget()));
            doc.add(new Paragraph("Style: " + state.getDateStyle()));
            doc.add(new Paragraph(""));

            @SuppressWarnings("unchecked")
            Map<String, Object> cafe = (Map<String, Object>) state.value(DatePlanState.SELECTED_CAFE).orElse(null);
            @SuppressWarnings("unchecked")
            Map<String, Object> spot = (Map<String, Object>) state.value(DatePlanState.SELECTED_SPOT).orElse(null);
            @SuppressWarnings("unchecked")
            Map<String, Object> restaurant = (Map<String, Object>) state.value(DatePlanState.SELECTED_RESTAURANT).orElse(null);

            if (cafe != null) doc.add(new Paragraph("Afternoon Tea: " + cafe.get("name")));
            if (spot != null) doc.add(new Paragraph("Sightseeing: " + spot.get("name")));
            if (restaurant != null) doc.add(new Paragraph("Dinner: " + restaurant.get("name")));

            doc.add(new Paragraph(""));
            doc.add(new Paragraph("Generated by AI Love Agent - " + date));

            log.info("PDF generated: {}", pdfPath);
            return pdfPath;

        } catch (Exception e) {
            log.error("PDF generation failed", e);
            return null;
        }
    }
}
